### ISSUE TITLE
About Category-level segmentation (beta)

### ISSUE THREAD

**Issue by Guptajakala** [scenenn/scenenn#7]
Why is this called beta version? Is there anything that needs to take special care?

**Comment by songuke** [comment]
We called it beta just because category-level segmentation with NYUv2 40 class labels is only published not long after SceneNN is released in 2016 (it mainly contains instance segmentation with free-form labels at that time). We subsequently use them in our later works (CVPR'18, WACV'19, CVPR'19, see publication section in http://www.scenenn.net/). It should have no problem to use.

**Comment by Guptajakala** [comment]
Thanks! I will close this.
